INSERT INTO ingredient (ingredient_name) VALUES ('butter');
INSERT INTO ingredient (ingredient_name) VALUES ('apple');
INSERT INTO ingredient (ingredient_name) VALUES ('sugar');
INSERT INTO ingredient (ingredient_name) VALUES ('egg');
INSERT INTO ingredient (ingredient_name) VALUES ('buttermilk');
INSERT INTO ingredient (ingredient_name) VALUES ('ginger');
INSERT INTO ingredient (ingredient_name) VALUES ('flour');
INSERT INTO ingredient (ingredient_name) VALUES ('ground ginger');
INSERT INTO ingredient (ingredient_name) VALUES ('baking powder');
INSERT INTO ingredient (ingredient_name) VALUES ('soda');
INSERT INTO ingredient (ingredient_name) VALUES ('icing sugar');
INSERT INTO ingredient (ingredient_name) VALUES ('custard');
INSERT INTO ingredient (ingredient_name) VALUES ('chocolate cake');
INSERT INTO ingredient (ingredient_name) VALUES ('coffee liqueur');
INSERT INTO ingredient (ingredient_name) VALUES ('coffee');
INSERT INTO ingredient (ingredient_name) VALUES ('sponge finger');
INSERT INTO ingredient (ingredient_name) VALUES ('cocoa powder');
INSERT INTO ingredient (ingredient_name) VALUES ('coffee granule');
INSERT INTO ingredient (ingredient_name) VALUES ('dark chocolate');
INSERT INTO ingredient (ingredient_name) VALUES ('salted butter');
INSERT INTO ingredient (ingredient_name) VALUES ('egg yolk');
INSERT INTO ingredient (ingredient_name) VALUES ('caster sugar');
INSERT INTO ingredient (ingredient_name) VALUES ('mascarpone');
INSERT INTO ingredient (ingredient_name) VALUES ('double cream');
INSERT INTO ingredient (ingredient_name) VALUES ('dark brown sugar');
INSERT INTO ingredient (ingredient_name) VALUES ('spaghetti');
INSERT INTO ingredient (ingredient_name) VALUES ('black peppercorn');
INSERT INTO ingredient (ingredient_name) VALUES ('parmesan');
INSERT INTO ingredient (ingredient_name) VALUES ('sausage');
INSERT INTO ingredient (ingredient_name) VALUES ('olive oil');
INSERT INTO ingredient (ingredient_name) VALUES ('onion');
INSERT INTO ingredient (ingredient_name) VALUES ('garlic clove');
INSERT INTO ingredient (ingredient_name) VALUES ('fennel seed');
INSERT INTO ingredient (ingredient_name) VALUES ('oregano');
INSERT INTO ingredient (ingredient_name) VALUES ('chilli flake');
INSERT INTO ingredient (ingredient_name) VALUES ('passata');
INSERT INTO ingredient (ingredient_name) VALUES ('tomato');
INSERT INTO ingredient (ingredient_name) VALUES ('bay leaf');
INSERT INTO ingredient (ingredient_name) VALUES ('milk');
INSERT INTO ingredient (ingredient_name) VALUES ('nutmeg');
INSERT INTO ingredient (ingredient_name) VALUES ('spinach');
INSERT INTO ingredient (ingredient_name) VALUES ('basil');
INSERT INTO ingredient (ingredient_name) VALUES ('lasagne sheet');
INSERT INTO ingredient (ingredient_name) VALUES ('cheddar');
INSERT INTO ingredient (ingredient_name) VALUES ('mozzarella');
INSERT INTO ingredient (ingredient_name) VALUES ('vegetable oil');
INSERT INTO ingredient (ingredient_name) VALUES ('paneer');
INSERT INTO ingredient (ingredient_name) VALUES ('garlic');
INSERT INTO ingredient (ingredient_name) VALUES ('hot chilli powder');
INSERT INTO ingredient (ingredient_name) VALUES ('ground cumin');
INSERT INTO ingredient (ingredient_name) VALUES ('fenugreek seed');
INSERT INTO ingredient (ingredient_name) VALUES ('garam masala');
INSERT INTO ingredient (ingredient_name) VALUES ('potato');
INSERT INTO ingredient (ingredient_name) VALUES ('pea');
INSERT INTO ingredient (ingredient_name) VALUES ('cashew nut butter');
INSERT INTO ingredient (ingredient_name) VALUES ('pastry sheet');
INSERT INTO ingredient (ingredient_name) VALUES ('nigella seed');
INSERT INTO ingredient (ingredient_name) VALUES ('pilau rice');
INSERT INTO ingredient (ingredient_name) VALUES ('chicken');
INSERT INTO ingredient (ingredient_name) VALUES ('penne');
INSERT INTO ingredient (ingredient_name) VALUES ('parsley');
INSERT INTO ingredient (ingredient_name) VALUES ('sunflower oil');
INSERT INTO ingredient (ingredient_name) VALUES ('pork sausage');
INSERT INTO ingredient (ingredient_name) VALUES ('golden caster sugar');
INSERT INTO ingredient (ingredient_name) VALUES ('tomato puree');
INSERT INTO ingredient (ingredient_name) VALUES ('red wine vinegar');
INSERT INTO ingredient (ingredient_name) VALUES ('beef stock');
INSERT INTO ingredient (ingredient_name) VALUES ('duck fat');
INSERT INTO ingredient (ingredient_name) VALUES ('maldon salt');
INSERT INTO ingredient (ingredient_name) VALUES ('sprigs thyme');
INSERT INTO ingredient (ingredient_name) VALUES ('cider');
INSERT INTO ingredient (ingredient_name) VALUES ('mustard powder');
INSERT INTO ingredient (ingredient_name) VALUES ('beef top rump joint');
INSERT INTO ingredient (ingredient_name) VALUES ('carrot');