INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 1, '50g', 'extra for the ramekins');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 2, '1', 'large, peeled, cored and finely chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 3, '75g', 'light brown muscovado');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 1, '140g', 'softened');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 3, '100g', 'light brown muscovado')
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 4, '1', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 5, '125ml', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 6, '2', 'balls preserved stem gigner, finely chopped, plus 1 tbsp syrup from jar');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 7, '100g', 'plain, plus extra for dusting');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 8, '1 1/2 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 9, '1/2 tsp', '') ;
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 10, '1/2 tsp', 'bicarbonate');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 11, '', 'for dusting');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (100, 12, '', 'to serve');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 13, '300g', 'cut into 3cm pieces');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 14, '70ml', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 15, '250ml', 'cooled');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 16, '200g', 'shop-bought');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 17, '2 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 12, '500g', 'fresh and shop-bought');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 18, '3 tbsp', 'instant');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 19, '200g', 'finely chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 20, '100g', 'cubed and softened');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 21, '2', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 22, '65g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 14, '40ml', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 23, '150g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 24, '200ml', 'for tiramisu filling');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 24, '400ml', 'for the brown sugar cream');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (101, 25, '2 tbsp', 'soft');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (102, 26, '200g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (102, 1, '25g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (102, 27, '2 tsp', 'whole');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (102, 28, '50g', 'finely grated');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 29, '12', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 30, '2 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 31, '2', 'chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 32, '4', 'crushed');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 33, '2 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 34, '2 tsp', 'dried and chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 35, '1/2 tsp', 'optional');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 3, '1 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 36, '500ml', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 37, '400g', 'chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 1, '100g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 38, '2', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 39, '1l', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 40, '1/4', 'fresh and finely grated');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 41, '100g', 'baby');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 42, '', 'handful and leaves torn');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 28, '50g', 'grated');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 43, '250g', 'dried and 12 sheets');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 44, '50g', 'grated');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (103, 45, '150g', 'torn into small pieces');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 46, '2 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 47, '440g', 'cut into 2cm cubes');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 1, '4 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 31, '2', 'large and finely sliced');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 32, '2', 'large and crushed');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 48, '1', 'thumb-sized and finely grated');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 49, '1/2 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 50, '2 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 51, '2 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 52, '1/2 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 37, '2x400g', 'in cans and chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 22, '1 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 53, '300g', 'peeled and cut into 2cm cubes');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 41, '150g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 54, '', 'frozen');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 24, '100ml', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 55, '2 tbsp', 'cashew');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 7, '', 'plain, for dusting');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 56, '320g', 'all-butter puff');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 4, '2', '1 whole and 1 yolk, lightly beaten together');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 57, '2 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (104, 58, '', 'to serve');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 30, '4 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 31, '1', 'finely chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 32, '2', 'crushed');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 35, '1/4 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 37, '2x400g', 'in cans and chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 22, '1 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 23, '6 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 59, '4', 'breast, skinless and sliced into strips');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 60, '300g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 44, '70g', 'mature and grated');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 45, '50g', 'grated');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (105, 61, '1/2', 'small bunch and finely chopped');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 62, '1 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 63, '8', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 1, '25g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 31, '2', 'finely sliced');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 64, '', 'pinch');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 7, '2 tbsp', 'plain');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 65, '1 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 66, '1 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 67, '500 ml', );
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 54, '', 'to serve (optional');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 53, '1.25kg', 'King Edwards or Maris Piper potatoes, cut into large chunks');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 39, '150ml', 'whole');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 1, '25g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (106, 44, '25g', 'mature and coarsely grated (optional)');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (107, 53, '1kg', 'Maris Piper potatoes');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (107, 68, '100g', 'for a luxurious taste');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (107, 7, '2 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (107, 69, '', 'to serve');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (108, 7, '200g', 'plain');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (108, 4, '3', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (108, 39, '300ml', 'whole');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (108, 30, '2 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (109, 53, '6', 'medium flory potatoes, such as Maris Piper');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (109, 1, '25g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (109, 30, '2 tbsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (109, 32, '2', 'bashed');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (109, 70, 'few', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (109, 71, '300ml', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (109, 59, '300ml', 'stock');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (110, 7, '1 tsp', 'plain');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (110, 72, '1 tsp', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (110, 73, '950g', '');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (110, 31, '1', 'cut into 8 wedges');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (110, 74, '500g', 'halved lengthways');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (110, 7, '1 tbsp', 'plain');
INSERT INTO recipe_ingredient (recipe_id, ingredient_id, rec_ing_amount, rec_ing_prep) VALUES (110, 67, '250ml', '');